onboarding = false

[ui]
status_indicators = "symbols"
prompt_new_tab_name = false

[ui.toast]
delivery = "herdr"

[keys]
prefix = "ctrl+f"
previous_tab = "prefix+f"
last_pane = "prefix+space"
#next_workspace = "prefix+space"
#previous_workspace = "prefix+shift+space"
next_agent = "prefix+a"
previous_agent = "prefix+shift+a"
navigate_workspace_up = "k"
navigate_workspace_down = "j"
navigate_pane_up = "shift+k"
navigate_pane_down = "shift+j"
## Does not work with Finnish layout
# switch_workspace = "prefix+shift+1..9"

[theme]
name = "terminal"
auto_switch = false

[theme.custom]
selection_bg = "#463f5d"

[[keys.command]]
key = 'prefix+!'
type = "shell"
description = 'switch to workspace 1'
command = 'herdr workspace focus $(herdr workspace list | jq -r ".result.workspaces[]|select(.number==1)|.workspace_id")'

[[keys.command]]
key = 'prefix+"'
type = "shell"
description = 'switch to workspace 2'
command = 'herdr workspace focus $(herdr workspace list | jq -r ".result.workspaces[]|select(.number==2)|.workspace_id")'

[[keys.command]]
key = 'prefix+#'
type = "shell"
description = 'switch to workspace 3'
command = 'herdr workspace focus $(herdr workspace list | jq -r ".result.workspaces[]|select(.number==3)|.workspace_id")'

[[keys.command]]
key = 'prefix+¤'
type = "shell"
description = 'switch to workspace 4'
command = 'herdr workspace focus $(herdr workspace list | jq -r ".result.workspaces[]|select(.number==4)|.workspace_id")'

[[keys.command]]
key = 'prefix+%'
type = "shell"
description = 'switch to workspace 5'
command = 'herdr workspace focus $(herdr workspace list | jq -r ".result.workspaces[]|select(.number==5)|.workspace_id")'

[[keys.command]]
key = 'prefix+&'
type = "shell"
description = 'switch to workspace 6'
command = 'herdr workspace focus $(herdr workspace list | jq -r ".result.workspaces[]|select(.number==6)|.workspace_id")'

[[keys.command]]
key = 'prefix+/'
type = "shell"
description = 'switch to workspace 7'
command = 'herdr workspace focus $(herdr workspace list | jq -r ".result.workspaces[]|select(.number==7)|.workspace_id")'

[[keys.command]]
key = 'prefix+('
type = "shell"
description = 'switch to workspace 8'
command = 'herdr workspace focus $(herdr workspace list | jq -r ".result.workspaces[]|select(.number==8)|.workspace_id")'

[[keys.command]]
key = 'prefix+)'
type = "shell"
description = 'switch to workspace 9'
command = 'herdr workspace focus $(herdr workspace list | jq -r ".result.workspaces[]|select(.number==9)|.workspace_id")'
